apiVersion: v1
kind: Service
metadata:
  name: k8s-db
  labels:
    app: k8s-db
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8s-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-db
  labels:
    app: k8s-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-db
  template:
    metadata:
      labels:
        app: k8s-db
    spec:
      containers:
        - name: k8s-db
          image: com.tomoyadeng/k8s-db:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: username
            - name: MYQL_PASSWD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password