apiVersion: v1
kind: PersistentVolume
metadata:
  name: master-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: master
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/mysql/data/master
    server: 192.168.99.103
  