apiVersion: v1
kind: PersistentVolume
metadata:
  name: replica-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: replica
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/mysql/data/replica
    server: 192.168.99.103
  