spring:
  profiles: k8s
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/k8s?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYQL_PASSWD}
